### PR TITLE
Change destination to use SQL - not actual DB file

### PR DESCRIPTION
**Pull request by unRARed**
This currently blows up because it's expecting Sqlite-compatible SQL statements rather than an actual Sqlite database. I simply opened the file with `sqlite3` CLI, dumped the data and overwrote the file here.

Seed output:

Screen Shot 2020-03-01 at 1 20 25 PM

Successful login with "user1@afs.com" account:

Screen Shot 2020-03-01 at 1 21 37 PM

### CODE REVIEW

**Comment by bwentzloff** [comment]
Oh duh. Sorry. I’ll fix that shortly

**Comment by unRARed** [comment]
Having a second, pre-drafted league with some fake player data would be nice if it's not too much trouble from your end.

**Comment by unRARed** [comment]
I added the player insert statements from the old dump.

Seems to have worked:

Screen Shot 2020-03-01 at 2 07 44 PM

**Comment by unRARed** [comment]
Per last commit: Screen Shot 2020-03-01 at 3 40 44 PM
Screen Shot 2020-03-01 at 3 40 27 PM

**Comment by unRARed** [comment]
Seems like there might be something preventing the draft from executing locally. I'll take a look at the controller and see if I can figure it out.

**Comment by bwentzloff** [comment]
You're awesome. Thanks. The draft probably isn't happening because there's a cron job that advances drafts. It's this endpoint: `Route::get('league/updateDraftStatus', 'LeagueController@updateDraftStatuses');` Just hit that locally and the draft will advance.

**Pull request merged**
